bcgov/moh-common-styles

projects/common/captcha/src/captcha.component.spec.ts
projects/common/lib/components/address/address.component.html
projects/common/lib/components/address/address.component.spec.ts
projects/common/lib/components/address/address.component.ts
projects/common/lib/components/city/city.component.html
projects/common/lib/components/city/city.component.spec.ts
projects/common/lib/components/city/city.component.ts
projects/common/lib/components/country/country.component.html
projects/common/lib/components/country/country.component.spec.ts
projects/common/lib/components/country/country.component.ts
projects/common/lib/components/dropdown/dropdown.component.spec.ts
projects/common/lib/components/password/password.component.spec.ts
projects/common/lib/components/postal-code/postal-code.component.html
projects/common/lib/components/postal-code/postal-code.component.ts
projects/common/lib/components/province/province.component.html
projects/common/lib/components/province/province.component.spec.ts
projects/common/lib/components/province/province.component.ts
projects/common/lib/components/street/street.component.html
projects/common/lib/components/street/street.component.spec.ts
projects/common/lib/components/street/street.component.ts
projects/common/lib/components/toggle/toggle.component.spec.ts
projects/common/lib/shared-core.module.ts
projects/common/public_api.ts
projects/common/services/src/geocoder.service.ts

Please review prior to merging with master

Address separation

---

projects/common/lib/components/button/button.component.html
projects/common/lib/components/button/button.component.spec.ts
projects/common/lib/components/button/button.component.ts
projects/common/lib/components/checkbox/checkbox.component.html
projects/common/lib/components/checkbox/checkbox.component.spec.ts
projects/common/lib/components/checkbox/checkbox.component.ts
projects/common/lib/components/consent-modal/consent-modal.component.html
projects/common/lib/components/consent-modal/consent-modal.component.spec.ts
projects/common/lib/components/consent-modal/consent-modal.component.ts
projects/common/lib/components/name/name.component.html
projects/common/lib/components/name/name.component.scss
projects/common/lib/components/name/name.component.spec.ts
projects/common/lib/components/name/name.component.ts
projects/common/lib/components/phone-number/phone-number.component.html
projects/common/lib/components/phone-number/phone-number.component.spec.ts
projects/common/lib/components/phone-number/phone-number.component.ts
projects/common/lib/components/radio/radio.component.html
projects/common/lib/components/radio/radio.component.spec.ts
projects/common/lib/components/radio/radio.component.ts
projects/common/lib/shared-core.module.ts

Created Button, Checkbox, Consent Modal, Radio, Name and Phone Number components

Created new components 

---

projects/common/lib/components/date/date.component.html
projects/common/lib/components/date/date.component.ts
projects/common/lib/models/error-message.interface.ts
projects/common/public_api.ts

Needed for next release of MSP enrolment - default messages exist in component and can be modified as required

feat: added ability to modify messages in date rather than replace.

---

projects/common/lib/models/person.model.ts

Fixed format string to work with the format function from date-fns module

fix: Date format string modified to use format from date-fns module

---

projects/common/lib/models/abstract-form-control.ts

V3 fix abstract control

---

projects/common/lib/components/date/date.component.ts
projects/common/lib/components/email/email.component.ts
projects/common/lib/components/phone-number/phone-number.component.ts
projects/common/lib/components/sin/sin.component.ts
projects/common/lib/models/abstract-form-control.ts
projects/common/lib/models/abstract-form.ts

V3 updates

---

projects/common/lib/components/email/email.component.ts

Reverts bcgov/moh-common-styles#88

Revert "fix: email validation for printable ascii characters"

---

projects/common/helpers/test-helpers.ts
projects/common/lib/components/city/city.component.spec.ts
projects/common/lib/components/phn/phn.component.spec.ts
projects/common/lib/components/province/province.component.spec.ts
projects/common/lib/components/radio/radio.component.html
projects/common/lib/components/radio/radio.component.scss
projects/common/lib/components/radio/radio.component.spec.ts
projects/common/lib/components/radio/radio.component.ts
projects/common/lib/components/sin/sin.component.spec.ts
projects/common/lib/components/street/street.component.spec.ts

Please review changes - fix tabbing for radio button component when used in reactive forms.

fix(radio): fix tabbing when component used with reactive forms

---

projects/common/lib/components/address-validator/address-validator.component.html
projects/common/lib/components/address-validator/address-validator.component.spec.ts
projects/common/lib/components/address-validator/address-validator.component.ts
projects/common/lib/components/geocoder-input/geocoder-input.component.ts
projects/common/lib/shared-core.module.ts
projects/common/test.ts

Tested in BCP, and all appears to be working.

DEMCL-21: Added `address-validator` component.

---

projects/common/lib/components/address-validator/address-validator.component.html
projects/common/lib/components/address-validator/address-validator.component.spec.ts

Found solution here: https://github.com/valor-software/ngx-bootstrap/issues/5826#issuecomment-670189353

fix: DEMCL-24: Reduced typeaheadMinLength to 0, to eliminate error.

---

projects/common/captcha/src/captcha.component.html
projects/common/captcha/src/captcha.component.scss

What I did:
1) Changed attributes and tags for accessibility
2) Restyled, removing most inline styles, unnecessary tags. and floats / clears. Added responsiveness
3) Tested with axe, axe-beta (Deque), and NVDM screen reader
>## Old Captcha
>## New Captcha (same behavior on Chrome, Edge, IE11, Firefox)

feat: DEMCL-22: Update captcha for accessibility, restyle

---

projects/common/captcha/src/captcha.component.ts
projects/common/lib/components/file-uploader/file-uploader.component.ts
projects/common/lib/components/password/password.component.ts
projects/common/lib/components/sin/sin.component.ts
projects/common/lib/components/street/street.component.ts
projects/common/lib/components/thumbnail/thumbnail.component.ts
projects/common/lib/services/default-page-guard.service.ts

Only commented them out in case anyone wants to keep them for debugging
This is to prevent users from seeing some of the follow logs

chore: comment out old logs

---

projects/common/lib/components/consent-modal/consent-modal.component.ts

chore: further commenting out of debug logs

---

projects/common/lib/components/file-uploader/file-uploader.component.ts

chore: comment debug log in file uploader

---

projects/common/lib/components/sample-modal/sample-modal.component.html

DEA11Y-23: Fix aria-labelledby use

---

projects/common/lib/components/form-action-bar/form-action-bar.component.scss

Hi there,
Sorry I thought I've pushed my changes earlier but I forgot there's a template for the commit.
Please check the minor change for the updated style for continue button.
Regards,
Cyril

fix: DEA11Y-15-update: Updated style for continue

---

projects/common/lib/components/file-uploader/file-uploader.component.html
projects/common/lib/components/file-uploader/file-uploader.component.scss

Prevents "missing or inappropriate role" axe error

DEA11Y-35: Change label to button, adjust styles for a11y

---

projects/common/lib/components/date/date.component.html

fix: a11y changes for date fields

---

projects/common/lib/components/sin/sin.component.ts

fix: prevent submissions of SINs that start with 0

---

projects/common/captcha/src/captcha.component.ts
projects/common/lib/components/accordion/accordion.component.html
projects/common/lib/components/address-validator/address-validator.component.ts
projects/common/lib/components/address/address.component.html
projects/common/lib/components/address/address.component.ts
projects/common/lib/components/button-group/button-group.component.ts
projects/common/lib/components/consent-modal/consent-modal.component.ts
projects/common/lib/components/core-breadcrumb/core-breadcrumb.component.ts
projects/common/lib/components/date/date.component.ts
projects/common/lib/components/datepicker/datepicker.component.ts
projects/common/lib/components/email/email.component.spec.ts
projects/common/lib/components/email/email.component.ts
projects/common/lib/components/file-uploader/file-uploader.component.ts
projects/common/lib/components/geocoder-input/geocoder-input.component.ts
projects/common/lib/components/password/password.component.ts
projects/common/lib/components/phone-number/phone-number.component.ts
projects/common/lib/components/postal-code/postal-code.component.ts
projects/common/lib/components/sin/sin.component.ts
projects/common/lib/components/street/street.component.spec.ts
projects/common/lib/components/street/street.component.ts
projects/common/lib/components/thumbnail/thumbnail.component.ts
projects/common/lib/components/xicon-button/xicon-button.component.ts
projects/common/lib/models/container.ts
projects/common/lib/services/default-page-guard.service.ts
projects/common/lib/services/logger.service.ts

Also fixed a spelling error in the address component

chore: cleanup commented out code and console logs

---

projects/common/lib/components/address/address.component.html
projects/common/lib/components/city/city.component.html
projects/common/lib/components/city/city.component.ts
projects/common/lib/components/date/date.component.html
projects/common/lib/components/email/email.component.html
projects/common/lib/components/email/email.component.ts
projects/common/lib/components/name/name.component.html
projects/common/lib/components/name/name.component.ts
projects/common/lib/components/phn/phn.component.html
projects/common/lib/components/phn/phn.component.ts
projects/common/lib/components/postal-code/postal-code.component.html
projects/common/lib/components/postal-code/postal-code.component.ts
projects/common/lib/components/radio/radio.component.html
projects/common/lib/components/radio/radio.component.ts
projects/common/lib/components/street/street.component.html
projects/common/lib/components/street/street.component.ts

fix: add missing or fix existing required flags

---

projects/common/lib/components/address/address.component.html
projects/common/lib/components/address/address.component.ts
projects/common/lib/components/country/country.component.html
projects/common/lib/components/country/country.component.ts
projects/common/lib/components/province/province.component.html
projects/common/lib/components/province/province.component.ts

Will need to ensure the PDF has the same format as before when all the a11y changes get properly tested

fix: fix a11y issues with province and country dropdowns

---

projects/common/lib/components/checkbox/checkbox.component.html

fix: add margin and padding

---

projects/common/lib/components/file-uploader/file-uploader.component.html

Pretty straightforward change, requested by test team

fix: make fileuploader cloud icon clickable
